version: '3'
services:
  app:
    image: node:18-alpine
    command: sh -c "yarn install && yarn run dev"
    ports:
      - 3000
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DB: todos
    networks:
      - app_network
  app2:
    image: node:18-alpine
    command: sh -c "yarn install && yarn run dev"
    ports:
      - 3000
    working_dir: /app
    volumes:
      - ./app2/:/app
    environment:
      MYSQL_HOST: mysql2
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DB: todos
    networks:
      - app_network
  mysql2:
    image: mysql:8.0
    volumes:
      - todo-mysql-data2:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: todos
    networks:
      - app_network
  mysql:
    image: mysql:8.0
    volumes:
      - todo-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: todos
    networks:
      - app_network
  nginx:
    image: nginx:latest
    ports:
      - 8080:80
    depends_on:
      - app 
      - app2
    volumes:
      - ./nginx/:/etc/nginx/conf.d/
    networks:
      - app_network

networks:
  app_network:

volumes:
  todo-mysql-data:
  todo-mysql-data2:
